---

- hosts: dev
  become: yes
  remote_user: ec2-user
  tasks:
         - name: insert urls for dev in wp-config.php
           blockinfile:
                   dest: /var/www/html/wp-config.php
                   insertbefore: "/* That's all,"
                   block: |
                     define('WP_SITEURL','http://dev.{{ domain }}{{ tld }}');
                     define('WP_HOME','http://dev.{{ domain }}{{ tld }}');
                   state: absent
         - name: Update S3 code bucket
           command: aws s3 sync /var/www/html s3://{{ s3code }}/ --delete
         - name: insert urls for dev in wp-config.php
           blockinfile:
                   dest: /var/www/html/wp-config.php
                   insertbefore: "/* That's all,"
                   block: |
                     define('WP_SITEURL','http://dev.{{ domain }}{{ tld }}');
                     define('WP_HOME','http://dev.{{ domain }}{{ tld }}');
                   
