---
- hosts: dev
  become: yes
  remote_user: ec2-user
  tasks:
          - name: Remove default aws packages
            yum: name={{ item }} state=absent
            with_items:
                    - php-common
          - name: Install Apache.
            yum: name={{ item }} state=present
            with_items:
                    - httpd24
                    - php56
                    - php56-mysqlnd
          - name: Download Wordpress
            get_url: url=http://wordpress.org/wordpress-latest.tar.gz dest=/var/www/html/wordpress.tar.gz force=yes
          - name: Extract Wordpress
            command: "tar xzf /var/www/html/wordpress.tar.gz -C /var/www/html --strip-components 1"
          - name: make my directory tree readable
            file:
                    path: /var/www/html
                    mode: u=rwX,g=rX,o=rX
                    recurse: yes
                    owner: apache
                    group: apache
          - name: Make sure Apache is started now and at boot.
            service: name=httpd state=started enabled=yes
